//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infoline.OmixEntegrationApp.LogoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientFindParam", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ClientFindParam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CariKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CariUnvanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VergiNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TCNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirmaNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CariKodu {
            get {
                return this.CariKoduField;
            }
            set {
                if ((object.ReferenceEquals(this.CariKoduField, value) != true)) {
                    this.CariKoduField = value;
                    this.RaisePropertyChanged("CariKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CariUnvan {
            get {
                return this.CariUnvanField;
            }
            set {
                if ((object.ReferenceEquals(this.CariUnvanField, value) != true)) {
                    this.CariUnvanField = value;
                    this.RaisePropertyChanged("CariUnvan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string VergiNo {
            get {
                return this.VergiNoField;
            }
            set {
                if ((object.ReferenceEquals(this.VergiNoField, value) != true)) {
                    this.VergiNoField = value;
                    this.RaisePropertyChanged("VergiNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TCNO {
            get {
                return this.TCNOField;
            }
            set {
                if ((object.ReferenceEquals(this.TCNOField, value) != true)) {
                    this.TCNOField = value;
                    this.RaisePropertyChanged("TCNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string FirmaNo {
            get {
                return this.FirmaNoField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmaNoField, value) != true)) {
                    this.FirmaNoField = value;
                    this.RaisePropertyChanged("FirmaNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdClientFind", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AdClientFind : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CariKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CariUnvanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TicariAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TicariSoyadiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Eposta1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Eposta2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Eposta3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IlceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TckNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VergiNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VergiKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VergiDairesiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YetkiliKisi1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YetkiliKisi2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YetkiliKisi3Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CariKodu {
            get {
                return this.CariKoduField;
            }
            set {
                if ((object.ReferenceEquals(this.CariKoduField, value) != true)) {
                    this.CariKoduField = value;
                    this.RaisePropertyChanged("CariKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CariUnvan {
            get {
                return this.CariUnvanField;
            }
            set {
                if ((object.ReferenceEquals(this.CariUnvanField, value) != true)) {
                    this.CariUnvanField = value;
                    this.RaisePropertyChanged("CariUnvan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TicariAdi {
            get {
                return this.TicariAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.TicariAdiField, value) != true)) {
                    this.TicariAdiField = value;
                    this.RaisePropertyChanged("TicariAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TicariSoyadi {
            get {
                return this.TicariSoyadiField;
            }
            set {
                if ((object.ReferenceEquals(this.TicariSoyadiField, value) != true)) {
                    this.TicariSoyadiField = value;
                    this.RaisePropertyChanged("TicariSoyadi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Eposta1 {
            get {
                return this.Eposta1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Eposta1Field, value) != true)) {
                    this.Eposta1Field = value;
                    this.RaisePropertyChanged("Eposta1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Eposta2 {
            get {
                return this.Eposta2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Eposta2Field, value) != true)) {
                    this.Eposta2Field = value;
                    this.RaisePropertyChanged("Eposta2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Eposta3 {
            get {
                return this.Eposta3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Eposta3Field, value) != true)) {
                    this.Eposta3Field = value;
                    this.RaisePropertyChanged("Eposta3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Adres {
            get {
                return this.AdresField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresField, value) != true)) {
                    this.AdresField = value;
                    this.RaisePropertyChanged("Adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Ilce {
            get {
                return this.IlceField;
            }
            set {
                if ((object.ReferenceEquals(this.IlceField, value) != true)) {
                    this.IlceField = value;
                    this.RaisePropertyChanged("Ilce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Il {
            get {
                return this.IlField;
            }
            set {
                if ((object.ReferenceEquals(this.IlField, value) != true)) {
                    this.IlField = value;
                    this.RaisePropertyChanged("Il");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string TckNo {
            get {
                return this.TckNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TckNoField, value) != true)) {
                    this.TckNoField = value;
                    this.RaisePropertyChanged("TckNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string VergiNo {
            get {
                return this.VergiNoField;
            }
            set {
                if ((object.ReferenceEquals(this.VergiNoField, value) != true)) {
                    this.VergiNoField = value;
                    this.RaisePropertyChanged("VergiNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string VergiKodu {
            get {
                return this.VergiKoduField;
            }
            set {
                if ((object.ReferenceEquals(this.VergiKoduField, value) != true)) {
                    this.VergiKoduField = value;
                    this.RaisePropertyChanged("VergiKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string VergiDairesi {
            get {
                return this.VergiDairesiField;
            }
            set {
                if ((object.ReferenceEquals(this.VergiDairesiField, value) != true)) {
                    this.VergiDairesiField = value;
                    this.RaisePropertyChanged("VergiDairesi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string YetkiliKisi1 {
            get {
                return this.YetkiliKisi1Field;
            }
            set {
                if ((object.ReferenceEquals(this.YetkiliKisi1Field, value) != true)) {
                    this.YetkiliKisi1Field = value;
                    this.RaisePropertyChanged("YetkiliKisi1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string YetkiliKisi2 {
            get {
                return this.YetkiliKisi2Field;
            }
            set {
                if ((object.ReferenceEquals(this.YetkiliKisi2Field, value) != true)) {
                    this.YetkiliKisi2Field = value;
                    this.RaisePropertyChanged("YetkiliKisi2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string YetkiliKisi3 {
            get {
                return this.YetkiliKisi3Field;
            }
            set {
                if ((object.ReferenceEquals(this.YetkiliKisi3Field, value) != true)) {
                    this.YetkiliKisi3Field = value;
                    this.RaisePropertyChanged("YetkiliKisi3");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdShipFindParam", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AdShipFindParam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirmaNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CariKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SevkKoduField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirmaNo {
            get {
                return this.FirmaNoField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmaNoField, value) != true)) {
                    this.FirmaNoField = value;
                    this.RaisePropertyChanged("FirmaNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CariKodu {
            get {
                return this.CariKoduField;
            }
            set {
                if ((object.ReferenceEquals(this.CariKoduField, value) != true)) {
                    this.CariKoduField = value;
                    this.RaisePropertyChanged("CariKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SevkKodu {
            get {
                return this.SevkKoduField;
            }
            set {
                if ((object.ReferenceEquals(this.SevkKoduField, value) != true)) {
                    this.SevkKoduField = value;
                    this.RaisePropertyChanged("SevkKodu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdShipFindList", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AdShipFindList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CariKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CariUnvanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SevkKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SevkAciklamasiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SevkAdresiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SevkIlceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SevkIlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SevkPostaKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SevkEpostaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SevkTelefonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SevkIlgiliKisiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CariKodu {
            get {
                return this.CariKoduField;
            }
            set {
                if ((object.ReferenceEquals(this.CariKoduField, value) != true)) {
                    this.CariKoduField = value;
                    this.RaisePropertyChanged("CariKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CariUnvan {
            get {
                return this.CariUnvanField;
            }
            set {
                if ((object.ReferenceEquals(this.CariUnvanField, value) != true)) {
                    this.CariUnvanField = value;
                    this.RaisePropertyChanged("CariUnvan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SevkKodu {
            get {
                return this.SevkKoduField;
            }
            set {
                if ((object.ReferenceEquals(this.SevkKoduField, value) != true)) {
                    this.SevkKoduField = value;
                    this.RaisePropertyChanged("SevkKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SevkAciklamasi {
            get {
                return this.SevkAciklamasiField;
            }
            set {
                if ((object.ReferenceEquals(this.SevkAciklamasiField, value) != true)) {
                    this.SevkAciklamasiField = value;
                    this.RaisePropertyChanged("SevkAciklamasi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SevkAdresi {
            get {
                return this.SevkAdresiField;
            }
            set {
                if ((object.ReferenceEquals(this.SevkAdresiField, value) != true)) {
                    this.SevkAdresiField = value;
                    this.RaisePropertyChanged("SevkAdresi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SevkIlce {
            get {
                return this.SevkIlceField;
            }
            set {
                if ((object.ReferenceEquals(this.SevkIlceField, value) != true)) {
                    this.SevkIlceField = value;
                    this.RaisePropertyChanged("SevkIlce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string SevkIl {
            get {
                return this.SevkIlField;
            }
            set {
                if ((object.ReferenceEquals(this.SevkIlField, value) != true)) {
                    this.SevkIlField = value;
                    this.RaisePropertyChanged("SevkIl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string SevkPostaKodu {
            get {
                return this.SevkPostaKoduField;
            }
            set {
                if ((object.ReferenceEquals(this.SevkPostaKoduField, value) != true)) {
                    this.SevkPostaKoduField = value;
                    this.RaisePropertyChanged("SevkPostaKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string SevkEposta {
            get {
                return this.SevkEpostaField;
            }
            set {
                if ((object.ReferenceEquals(this.SevkEpostaField, value) != true)) {
                    this.SevkEpostaField = value;
                    this.RaisePropertyChanged("SevkEposta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string SevkTelefon {
            get {
                return this.SevkTelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.SevkTelefonField, value) != true)) {
                    this.SevkTelefonField = value;
                    this.RaisePropertyChanged("SevkTelefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string SevkIlgiliKisi {
            get {
                return this.SevkIlgiliKisiField;
            }
            set {
                if ((object.ReferenceEquals(this.SevkIlgiliKisiField, value) != true)) {
                    this.SevkIlgiliKisiField = value;
                    this.RaisePropertyChanged("SevkIlgiliKisi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdItemsFindParam", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AdItemsFindParam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirmaNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrunKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrunAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarkodField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirmaNo {
            get {
                return this.FirmaNoField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmaNoField, value) != true)) {
                    this.FirmaNoField = value;
                    this.RaisePropertyChanged("FirmaNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UrunKodu {
            get {
                return this.UrunKoduField;
            }
            set {
                if ((object.ReferenceEquals(this.UrunKoduField, value) != true)) {
                    this.UrunKoduField = value;
                    this.RaisePropertyChanged("UrunKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UrunAdi {
            get {
                return this.UrunAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.UrunAdiField, value) != true)) {
                    this.UrunAdiField = value;
                    this.RaisePropertyChanged("UrunAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Barkod {
            get {
                return this.BarkodField;
            }
            set {
                if ((object.ReferenceEquals(this.BarkodField, value) != true)) {
                    this.BarkodField = value;
                    this.RaisePropertyChanged("Barkod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdItemsFindList", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AdItemsFindList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrunKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrunAciklamasi1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrunAciklamasi2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrunAciklamasi3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BirimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MalzemeTuruAciklamasiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MalzemeTuruKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StokTakipTipiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarkodField;
        
        private double BirimMaliyetField;
        
        private double BirimFiyatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarkaKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarkaAciklamasiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KategoriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UrunKodu {
            get {
                return this.UrunKoduField;
            }
            set {
                if ((object.ReferenceEquals(this.UrunKoduField, value) != true)) {
                    this.UrunKoduField = value;
                    this.RaisePropertyChanged("UrunKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UrunAciklamasi1 {
            get {
                return this.UrunAciklamasi1Field;
            }
            set {
                if ((object.ReferenceEquals(this.UrunAciklamasi1Field, value) != true)) {
                    this.UrunAciklamasi1Field = value;
                    this.RaisePropertyChanged("UrunAciklamasi1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UrunAciklamasi2 {
            get {
                return this.UrunAciklamasi2Field;
            }
            set {
                if ((object.ReferenceEquals(this.UrunAciklamasi2Field, value) != true)) {
                    this.UrunAciklamasi2Field = value;
                    this.RaisePropertyChanged("UrunAciklamasi2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UrunAciklamasi3 {
            get {
                return this.UrunAciklamasi3Field;
            }
            set {
                if ((object.ReferenceEquals(this.UrunAciklamasi3Field, value) != true)) {
                    this.UrunAciklamasi3Field = value;
                    this.RaisePropertyChanged("UrunAciklamasi3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Birim {
            get {
                return this.BirimField;
            }
            set {
                if ((object.ReferenceEquals(this.BirimField, value) != true)) {
                    this.BirimField = value;
                    this.RaisePropertyChanged("Birim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string MalzemeTuruAciklamasi {
            get {
                return this.MalzemeTuruAciklamasiField;
            }
            set {
                if ((object.ReferenceEquals(this.MalzemeTuruAciklamasiField, value) != true)) {
                    this.MalzemeTuruAciklamasiField = value;
                    this.RaisePropertyChanged("MalzemeTuruAciklamasi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string MalzemeTuruKodu {
            get {
                return this.MalzemeTuruKoduField;
            }
            set {
                if ((object.ReferenceEquals(this.MalzemeTuruKoduField, value) != true)) {
                    this.MalzemeTuruKoduField = value;
                    this.RaisePropertyChanged("MalzemeTuruKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string StokTakipTipi {
            get {
                return this.StokTakipTipiField;
            }
            set {
                if ((object.ReferenceEquals(this.StokTakipTipiField, value) != true)) {
                    this.StokTakipTipiField = value;
                    this.RaisePropertyChanged("StokTakipTipi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Barkod {
            get {
                return this.BarkodField;
            }
            set {
                if ((object.ReferenceEquals(this.BarkodField, value) != true)) {
                    this.BarkodField = value;
                    this.RaisePropertyChanged("Barkod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public double BirimMaliyet {
            get {
                return this.BirimMaliyetField;
            }
            set {
                if ((this.BirimMaliyetField.Equals(value) != true)) {
                    this.BirimMaliyetField = value;
                    this.RaisePropertyChanged("BirimMaliyet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public double BirimFiyat {
            get {
                return this.BirimFiyatField;
            }
            set {
                if ((this.BirimFiyatField.Equals(value) != true)) {
                    this.BirimFiyatField = value;
                    this.RaisePropertyChanged("BirimFiyat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string MarkaKodu {
            get {
                return this.MarkaKoduField;
            }
            set {
                if ((object.ReferenceEquals(this.MarkaKoduField, value) != true)) {
                    this.MarkaKoduField = value;
                    this.RaisePropertyChanged("MarkaKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string MarkaAciklamasi {
            get {
                return this.MarkaAciklamasiField;
            }
            set {
                if ((object.ReferenceEquals(this.MarkaAciklamasiField, value) != true)) {
                    this.MarkaAciklamasiField = value;
                    this.RaisePropertyChanged("MarkaAciklamasi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Kategori {
            get {
                return this.KategoriField;
            }
            set {
                if ((object.ReferenceEquals(this.KategoriField, value) != true)) {
                    this.KategoriField = value;
                    this.RaisePropertyChanged("Kategori");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LogoService.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name Gelen from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCariList", ReplyAction="*")]
        Infoline.OmixEntegrationApp.LogoService.GetCariListResponse GetCariList(Infoline.OmixEntegrationApp.LogoService.GetCariListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCariList", ReplyAction="*")]
        System.Threading.Tasks.Task<Infoline.OmixEntegrationApp.LogoService.GetCariListResponse> GetCariListAsync(Infoline.OmixEntegrationApp.LogoService.GetCariListRequest request);
        
        // CODEGEN: Generating message contract since element name Gelen from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSevkAdresList", ReplyAction="*")]
        Infoline.OmixEntegrationApp.LogoService.GetSevkAdresListResponse GetSevkAdresList(Infoline.OmixEntegrationApp.LogoService.GetSevkAdresListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSevkAdresList", ReplyAction="*")]
        System.Threading.Tasks.Task<Infoline.OmixEntegrationApp.LogoService.GetSevkAdresListResponse> GetSevkAdresListAsync(Infoline.OmixEntegrationApp.LogoService.GetSevkAdresListRequest request);
        
        // CODEGEN: Generating message contract since element name Gelen from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMalzemeList", ReplyAction="*")]
        Infoline.OmixEntegrationApp.LogoService.GetMalzemeListResponse GetMalzemeList(Infoline.OmixEntegrationApp.LogoService.GetMalzemeListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMalzemeList", ReplyAction="*")]
        System.Threading.Tasks.Task<Infoline.OmixEntegrationApp.LogoService.GetMalzemeListResponse> GetMalzemeListAsync(Infoline.OmixEntegrationApp.LogoService.GetMalzemeListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCariListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCariList", Namespace="http://tempuri.org/", Order=0)]
        public Infoline.OmixEntegrationApp.LogoService.GetCariListRequestBody Body;
        
        public GetCariListRequest() {
        }
        
        public GetCariListRequest(Infoline.OmixEntegrationApp.LogoService.GetCariListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCariListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Infoline.OmixEntegrationApp.LogoService.ClientFindParam Gelen;
        
        public GetCariListRequestBody() {
        }
        
        public GetCariListRequestBody(Infoline.OmixEntegrationApp.LogoService.ClientFindParam Gelen) {
            this.Gelen = Gelen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCariListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCariListResponse", Namespace="http://tempuri.org/", Order=0)]
        public Infoline.OmixEntegrationApp.LogoService.GetCariListResponseBody Body;
        
        public GetCariListResponse() {
        }
        
        public GetCariListResponse(Infoline.OmixEntegrationApp.LogoService.GetCariListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCariListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Infoline.OmixEntegrationApp.LogoService.AdClientFind[] GetCariListResult;
        
        public GetCariListResponseBody() {
        }
        
        public GetCariListResponseBody(Infoline.OmixEntegrationApp.LogoService.AdClientFind[] GetCariListResult) {
            this.GetCariListResult = GetCariListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSevkAdresListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSevkAdresList", Namespace="http://tempuri.org/", Order=0)]
        public Infoline.OmixEntegrationApp.LogoService.GetSevkAdresListRequestBody Body;
        
        public GetSevkAdresListRequest() {
        }
        
        public GetSevkAdresListRequest(Infoline.OmixEntegrationApp.LogoService.GetSevkAdresListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSevkAdresListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Infoline.OmixEntegrationApp.LogoService.AdShipFindParam Gelen;
        
        public GetSevkAdresListRequestBody() {
        }
        
        public GetSevkAdresListRequestBody(Infoline.OmixEntegrationApp.LogoService.AdShipFindParam Gelen) {
            this.Gelen = Gelen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSevkAdresListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSevkAdresListResponse", Namespace="http://tempuri.org/", Order=0)]
        public Infoline.OmixEntegrationApp.LogoService.GetSevkAdresListResponseBody Body;
        
        public GetSevkAdresListResponse() {
        }
        
        public GetSevkAdresListResponse(Infoline.OmixEntegrationApp.LogoService.GetSevkAdresListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSevkAdresListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Infoline.OmixEntegrationApp.LogoService.AdShipFindList[] GetSevkAdresListResult;
        
        public GetSevkAdresListResponseBody() {
        }
        
        public GetSevkAdresListResponseBody(Infoline.OmixEntegrationApp.LogoService.AdShipFindList[] GetSevkAdresListResult) {
            this.GetSevkAdresListResult = GetSevkAdresListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMalzemeListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMalzemeList", Namespace="http://tempuri.org/", Order=0)]
        public Infoline.OmixEntegrationApp.LogoService.GetMalzemeListRequestBody Body;
        
        public GetMalzemeListRequest() {
        }
        
        public GetMalzemeListRequest(Infoline.OmixEntegrationApp.LogoService.GetMalzemeListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMalzemeListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Infoline.OmixEntegrationApp.LogoService.AdItemsFindParam Gelen;
        
        public GetMalzemeListRequestBody() {
        }
        
        public GetMalzemeListRequestBody(Infoline.OmixEntegrationApp.LogoService.AdItemsFindParam Gelen) {
            this.Gelen = Gelen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMalzemeListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMalzemeListResponse", Namespace="http://tempuri.org/", Order=0)]
        public Infoline.OmixEntegrationApp.LogoService.GetMalzemeListResponseBody Body;
        
        public GetMalzemeListResponse() {
        }
        
        public GetMalzemeListResponse(Infoline.OmixEntegrationApp.LogoService.GetMalzemeListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMalzemeListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Infoline.OmixEntegrationApp.LogoService.AdItemsFindList[] GetMalzemeListResult;
        
        public GetMalzemeListResponseBody() {
        }
        
        public GetMalzemeListResponseBody(Infoline.OmixEntegrationApp.LogoService.AdItemsFindList[] GetMalzemeListResult) {
            this.GetMalzemeListResult = GetMalzemeListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : Infoline.OmixEntegrationApp.LogoService.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<Infoline.OmixEntegrationApp.LogoService.Service1Soap>, Infoline.OmixEntegrationApp.LogoService.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Infoline.OmixEntegrationApp.LogoService.GetCariListResponse Infoline.OmixEntegrationApp.LogoService.Service1Soap.GetCariList(Infoline.OmixEntegrationApp.LogoService.GetCariListRequest request) {
            return base.Channel.GetCariList(request);
        }
        
        public Infoline.OmixEntegrationApp.LogoService.AdClientFind[] GetCariList(Infoline.OmixEntegrationApp.LogoService.ClientFindParam Gelen) {
            Infoline.OmixEntegrationApp.LogoService.GetCariListRequest inValue = new Infoline.OmixEntegrationApp.LogoService.GetCariListRequest();
            inValue.Body = new Infoline.OmixEntegrationApp.LogoService.GetCariListRequestBody();
            inValue.Body.Gelen = Gelen;
            Infoline.OmixEntegrationApp.LogoService.GetCariListResponse retVal = ((Infoline.OmixEntegrationApp.LogoService.Service1Soap)(this)).GetCariList(inValue);
            return retVal.Body.GetCariListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Infoline.OmixEntegrationApp.LogoService.GetCariListResponse> Infoline.OmixEntegrationApp.LogoService.Service1Soap.GetCariListAsync(Infoline.OmixEntegrationApp.LogoService.GetCariListRequest request) {
            return base.Channel.GetCariListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Infoline.OmixEntegrationApp.LogoService.GetCariListResponse> GetCariListAsync(Infoline.OmixEntegrationApp.LogoService.ClientFindParam Gelen) {
            Infoline.OmixEntegrationApp.LogoService.GetCariListRequest inValue = new Infoline.OmixEntegrationApp.LogoService.GetCariListRequest();
            inValue.Body = new Infoline.OmixEntegrationApp.LogoService.GetCariListRequestBody();
            inValue.Body.Gelen = Gelen;
            return ((Infoline.OmixEntegrationApp.LogoService.Service1Soap)(this)).GetCariListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Infoline.OmixEntegrationApp.LogoService.GetSevkAdresListResponse Infoline.OmixEntegrationApp.LogoService.Service1Soap.GetSevkAdresList(Infoline.OmixEntegrationApp.LogoService.GetSevkAdresListRequest request) {
            return base.Channel.GetSevkAdresList(request);
        }
        
        public Infoline.OmixEntegrationApp.LogoService.AdShipFindList[] GetSevkAdresList(Infoline.OmixEntegrationApp.LogoService.AdShipFindParam Gelen) {
            Infoline.OmixEntegrationApp.LogoService.GetSevkAdresListRequest inValue = new Infoline.OmixEntegrationApp.LogoService.GetSevkAdresListRequest();
            inValue.Body = new Infoline.OmixEntegrationApp.LogoService.GetSevkAdresListRequestBody();
            inValue.Body.Gelen = Gelen;
            Infoline.OmixEntegrationApp.LogoService.GetSevkAdresListResponse retVal = ((Infoline.OmixEntegrationApp.LogoService.Service1Soap)(this)).GetSevkAdresList(inValue);
            return retVal.Body.GetSevkAdresListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Infoline.OmixEntegrationApp.LogoService.GetSevkAdresListResponse> Infoline.OmixEntegrationApp.LogoService.Service1Soap.GetSevkAdresListAsync(Infoline.OmixEntegrationApp.LogoService.GetSevkAdresListRequest request) {
            return base.Channel.GetSevkAdresListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Infoline.OmixEntegrationApp.LogoService.GetSevkAdresListResponse> GetSevkAdresListAsync(Infoline.OmixEntegrationApp.LogoService.AdShipFindParam Gelen) {
            Infoline.OmixEntegrationApp.LogoService.GetSevkAdresListRequest inValue = new Infoline.OmixEntegrationApp.LogoService.GetSevkAdresListRequest();
            inValue.Body = new Infoline.OmixEntegrationApp.LogoService.GetSevkAdresListRequestBody();
            inValue.Body.Gelen = Gelen;
            return ((Infoline.OmixEntegrationApp.LogoService.Service1Soap)(this)).GetSevkAdresListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Infoline.OmixEntegrationApp.LogoService.GetMalzemeListResponse Infoline.OmixEntegrationApp.LogoService.Service1Soap.GetMalzemeList(Infoline.OmixEntegrationApp.LogoService.GetMalzemeListRequest request) {
            return base.Channel.GetMalzemeList(request);
        }
        
        public Infoline.OmixEntegrationApp.LogoService.AdItemsFindList[] GetMalzemeList(Infoline.OmixEntegrationApp.LogoService.AdItemsFindParam Gelen) {
            Infoline.OmixEntegrationApp.LogoService.GetMalzemeListRequest inValue = new Infoline.OmixEntegrationApp.LogoService.GetMalzemeListRequest();
            inValue.Body = new Infoline.OmixEntegrationApp.LogoService.GetMalzemeListRequestBody();
            inValue.Body.Gelen = Gelen;
            Infoline.OmixEntegrationApp.LogoService.GetMalzemeListResponse retVal = ((Infoline.OmixEntegrationApp.LogoService.Service1Soap)(this)).GetMalzemeList(inValue);
            return retVal.Body.GetMalzemeListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Infoline.OmixEntegrationApp.LogoService.GetMalzemeListResponse> Infoline.OmixEntegrationApp.LogoService.Service1Soap.GetMalzemeListAsync(Infoline.OmixEntegrationApp.LogoService.GetMalzemeListRequest request) {
            return base.Channel.GetMalzemeListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Infoline.OmixEntegrationApp.LogoService.GetMalzemeListResponse> GetMalzemeListAsync(Infoline.OmixEntegrationApp.LogoService.AdItemsFindParam Gelen) {
            Infoline.OmixEntegrationApp.LogoService.GetMalzemeListRequest inValue = new Infoline.OmixEntegrationApp.LogoService.GetMalzemeListRequest();
            inValue.Body = new Infoline.OmixEntegrationApp.LogoService.GetMalzemeListRequestBody();
            inValue.Body.Gelen = Gelen;
            return ((Infoline.OmixEntegrationApp.LogoService.Service1Soap)(this)).GetMalzemeListAsync(inValue);
        }
    }
}
