using System;
using GeoAPI.Geometries;

namespace Infoline.WorkOfTime.BusinessData
{
    public partial class VWSRV_Service : InfolineTable
    {
        public Guid? PID { get; set;}
        public int? ServiceStatus { get; set;}
        public int? ServiceType { get; set;}
        public string ServiceCode { get; set;}
        public Guid? ServiceCategory { get; set;}
        public Guid? ServiceFixture { get; set;}
        public Guid? ServiceStationId { get; set;}
        public Guid? ServiceDeclarationFirm { get; set;}
        public Guid? ServiceDeclarationPerson { get; set;}
        public string ServiceDetail { get; set;}
        public string VerificationCode { get; set;}
        public bool? VerificationCodeConfirm { get; set;}
        public Guid? VerificationCodeConfirmPerson { get; set;}
        public IGeometry  VerificationCodeConfirmLocation { get; set;}
        public Guid? ServiceOperationPerson { get; set;}
        public DateTime? ServiceOperationDate { get; set;}
        public string ServiceOperationResultDetail { get; set;}
        public IGeometry  ServiceOperationLocation { get; set;}
        public DateTime? ServiceOperationComfirmDate { get; set;}
        public Guid? ServiceOperationComfirmPerson { get; set;}
        public string ServiceOperationComfirmDetail { get; set;}
        public int? ServiceOperationComfirmResult { get; set;}
        public IGeometry  CurrentLocation { get; set;}
        public int? CurrentLocationStatus { get; set;}
        public bool? AutoGenerated { get; set;}
        public string createdby_Title { get; set;}
        public string changedby_Title { get; set;}
        public string ServiceFixture_Title { get; set;}
        public string ServiceDeclarationFirm_Title { get; set;}
        public string VerificationCodeConfirmPerson_Title { get; set;}
        public string ServiceOperationPerson_Title { get; set;}
        public string ServiceOperationComfirmPerson_Title { get; set;}
        public string ServiceDeclarationPerson_Title { get; set;}
        public string ServiceType_Title { get; set;}
        public string ServiceOperationComfirmResult_Title { get; set;}
        public string ServiceStatus_Title { get; set;}
        public string ServiceCategory_Title { get; set;}
        public int? ResponseHour { get; set;}
    }
}
